name = "team9"
location = "westus"
project = "Project2"
environment = "test"
bastion_enables = "1"
allspark_data = {
  "location" = "westus"
  "nsg_id" = "/subscriptions/8d12a595-ad13-41df-bf17-0a5b9ad7aa90/resourceGroups/team9/providers/Microsoft.Network/networkSecurityGroups/team9_admin_nsg"
  "nsg_name" = "team9_admin_nsg"
  "resource_group_name" = "team9"
  "subnet_id" = "/subscriptions/8d12a595-ad13-41df-bf17-0a5b9ad7aa90/resourceGroups/team9/providers/Microsoft.Network/virtualNetworks/team9_vnet/subnets/team9_admin_subnet"
  "subnet_index" = "admin"
  "subnet_name" = "team9_admin_subnet"
  "tag_env" = "test"
  "tag_proj" = "Project2"
  "vnet_id" = "/subscriptions/8d12a595-ad13-41df-bf17-0a5b9ad7aa90/resourceGroups/team9/providers/Microsoft.Network/virtualNetworks/team9_vnet"
  "vnet_name" = "team9_vnet"
}
